apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: apr7-codgen-defaultmodelserver
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: apr7-codgen-defaultmodelserver
  name: apr7-codgen-defaultmodelserver
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
