apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: apr7-codgen-defaultmodelserver
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: apr7-codgen-defaultmodelserver
  name: apr7-codgen-defaultmodelserver
spec:
  port:
    targetPort: 8501
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: apr7-codgen-defaultmodelserver
    weight: 100
  wildcardPolicy: None
