apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: apr7-codgen-defaultmodelserver
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: apr7-codgen-defaultmodelserver
  name: apr7-codgen-defaultmodelserver
spec:
  ports:
    - port: 8501
      protocol: TCP
      targetPort: 8501
  selector:
    app.kubernetes.io/instance: apr7-codgen-defaultmodelserver
