apiVersion: batch/v1
kind: Job
metadata:
  name: dsp-clone-job-apr7-codgen-defaultmodelserver-gitops
spec:
  template:
    metadata:
      name: dsp-clone-job-apr7-codgen-defaultmodelserver-gitops
    spec:
      serviceAccountName: apr7-codgen-defaultmodelserver-dsp-job
      containers:
        - name: initialize-dsp
          image: quay.io/redhat-ai-dev/utils:latest
          command:
            - /bin/bash
            - -c
            - |
              NS=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
              oc wait -l statefulset=apr7-codgen-defaultmodelserver-notebook --for=condition=ready pod --timeout=300s
              oc exec  StatefulSet/apr7-codgen-defaultmodelserver-notebook -- git clone https://github.com/jdubrick-ai/apr7-codgen-defaultmodelserver
      restartPolicy: Never
